var sources = {
    planetes : [
        {
            "name"              : "Sun",
            "distance"          : "0",
            "size"              : "80000",
            "revolution"        : "0",
            "texture"           : "sunmap.jpg",
            "rotation"          : "0",
        },
        {
            "name"              : "Mercure",
            "distance"          : "58",
            "size"              : "4900",
            "revolution"        : "88",
            "texture"           : "mercuremap.jpg",
            "rotation"          : "59",
        },
        {
            "name"              : "Venus",
            "distance"          : "108",
            "size"              : "12104",
            "revolution"        : "224",
            "texture"           : "venusmap.jpg",
            "rotation"          : "243",
        },
        {
            "name"              : "Terre",
            "distance"          : "149",
            "size"              : "12756",
            "revolution"        : "365",
            "texture"           : "earthmap.jpg",
            "rotation"          : "1",
        },
        {
            "name"              : "Mars",
            "distance"          : "227",
            "size"              : "6788",
            "revolution"        : "687",
            "texture"           : "marsmap.jpg",
            "rotation"          : "1",
        },
        {
            "name"              : "Jupiter",
            "distance"          : "778",
            "size"              : "8000",
            "revolution"        : "4340",
            "texture"           : "jupitermap.jpg",
            "rotation"          : "0.41", 
        },
        {
            "name"              : "Saturne",
            "distance"          : "1426",
            "size"              : "4900",
            "revolution"        : "10585",
            "texture"           : "saturnemap.jpg",
            'rotation'          : "0.43",
        },
        {
            "name"              : "Uranus",
            "distance"          : "2871",
            "size"              : "51152",
            "revolution"        : "29736",
            "texture"           : "uranusmap.jpg",
            "rotation"           : "0.6",
        },
        {
            "name"              : "Neptune",
            "distance"          : "4498",
            "size"              : "49620",
            "revolution"        : "30660",
            "texture"           : "neptunemap.jpg",
            "rotation"           : "0,75",
        },
        {
            "name"              : "Pluton",
            "distance"          : "5960",
            "size"              : "2296",
            "revolution"        : "90155",
            "texture"           : "plutonmap.jpg",
            "rotation"          : "6.39",
        }
    ]
}